name: daisy-example
services:
  web:
    image: ghcr.io/witnium/daisy-example-web@sha256:1b9be580fbace09ca0acc713027d625e4e06a8495347c2c4e340731d9ff8edad
    ports: ["8080"]
    depends_on: [api]
    environment: [EXAMPLE_MESSAGE, API_URL, EXAMPLE_TOKEN, FILES_PATH]
    volumes: ["files:/data"]
    restart: unless-stopped
  api:
    image: ghcr.io/witnium/daisy-example-api@sha256:ae4c413df1770882abbdf80333fb7058dc4e6a2c8be8fb140bf77120d58425ab
    ports: ["8081"]
    depends_on: [postgres]
    environment: [DATABASE_URL, EXAMPLE_TOKEN, FILES_PATH, FAULT_FILL_CAP_BYTES, FAULT_FILL_FLOOR_BYTES]
    volumes: ["files:/data"]
    restart: unless-stopped
  worker:
    image: ghcr.io/witnium/daisy-example-worker@sha256:7a51b0f99e9438bddad625650466b707953779df1f664539c888df0b8218f0b3
    ports: ["8082"]
    depends_on: [api, postgres]
    environment: [DATABASE_URL, EXAMPLE_TOKEN, API_URL, FILES_PATH]
    volumes: ["files:/data"]
    restart: unless-stopped
  postgres:
    image: ghcr.io/witnium/daisy-example-postgres@sha256:598ed41d4a48b877f3f8380f25462956027838de3c149458581448a74b183658
    ports: ["5432"]
    environment: [POSTGRES_PASSWORD]
    volumes: ["database:/var/lib/postgresql/data"]
volumes:
  files: {}
  database: {}
